#!/bin/bash
ln -s /dev/pts/12 /dev/rm090-1
ln -s /dev/pts/15 /dev/rm090-2
ln -s /dev/pts/19 /dev/rm090-3
ln -s /dev/pts/20 /dev/rm090-4
ln -s /dev/pts/21 /dev/rm090-5
ln -s /dev/pts/22 /dev/rm090-6
ln -s /dev/pts/23 /dev/rm090-7
ln -s /dev/pts/24 /dev/rm090-8
ln -s /dev/pts/25 /dev/rm090-9
ln -s /dev/pts/26 /dev/rm090-10
